The city has almost no resources; there is no mining due to the special nature
of the bedrock, and farming can only be undertaken with dirt collected in the
Dungeon, so Spelunkers have to go into the Dungeon to find or harvest these
essential resources for the City.

==== Food

The vast majority of food comes from the Dungeon. Meats from various monsters
are highly valued. Fungi can be harvested from certain areas in the Dungeon and
are also highly valued. The citizens are able to grow certain crops on roof
tops and balconies (if they get enough light). Many citizens also grow their
own herbs and spices in their own homes. However, many spices can only be
obtained in the Dungeon as it turns out that certain monster parts are
themselves quite spicy and tasty. Certain molds are also very tasty, and
sometimes adventurers will find special nutritional plants in the Dungeon that
are both high in nutrients and taste. Some plants and fungi can even be used in
baking, replacing wheat and oats.

Some citizens do have farm animals for slaughter and milk, but these are few
and very expensive to keep. 

Salt can be found in the Dungeon in areas where the bedrock gives way to
mundane rock and allow water to deposit minerals.

To really vary the types, variety and quality of food, citizens rely heavily on
magic. Many mages can make a decent living simply by spicing up, and even
transmuting the food that is gathered in the Dungeon.

Monsters often posses foods that are not normally found in the Dungeon. For
instance, some tribes of dark elves, cave giants, and orcs sometimes possess
cheeses, baked goods, veal-like meats, and even alcoholic beverages. It is a
great source of mystery how these tribes obtain such riches.

Because food is scarce, nothing is wasted. Scraps and waste food is sold to
people who have farm animals that can eat them, and bones and sinews are sold
to various types of craftspersons.

==== Clothes

Most citizens wear hide or leather from monsters slain in the Dungeon. Various
fabrics do exist, but they are often much more expensive than leather. Cloth
can be made from hair or wool from certain monsters. Certain monsters sometimes
wear clothes made from wool, cotton or linen.


==== Corpses and dead bodies

Citizens are not buried when they die; they are treated as if they were a
corpse brought up from the Dungeon. This means that they are skinned so the
skin can be used leather. Fatty tissue is rendered into oils and soaps, certain
soft tissue is made into glue, bones are used in the production of cement or as
parts of tools.  No part of a corpse is left unused. Even the blood can be used
as bait, to make blood sausage, or be purified into potable water. Human meat
is normally not consumed by humans in the City, but it is sometimes used as
bait to lure out monsters in the Dungeon; sometimes it is sterilized by magic
and used to feed livestock. During famine and other bad periods, the lower
classes sometimes have to resort to eating human flesh.

==== Water

The Dungeon is home to many lakes and streams. The main trouble is that these
often serve as watering holes for monsters. Some caves and caverns have water
dripping from the ceilings or slowly condensing on the walls and some
spelunkers make a living by collecting that water. It is a slow process, but it
is relatively safe and it only requires a few simple containers.

Magic and alchemy can be used to purify water and even distil water from blood
and other fluids.


==== Metal

The Dungeon is the only source of metal available. For some reason, many
monsters carry weapons and other gear containing metal. Where they get it is a
mystery as no adventurers have ever found any mines operated by monsters.

Certain monsters have metal-like hides, bones and teeth. These are very
valuable. Additionally, magic can be used to transmute bone and certain monster
scales, claws, and bones into metal, but these methods are quite time consuming
and expensive.

Sometimes raw ores can be mined from certain areas of the Dungeon, but this is
very dangerous and will require guards and lookouts because of the noise. Such
mines are always temporary because of the shifts the Dungeon regularly
undergoes. Moreover smelting raw ore can be a very fuel consuming and polluting
process, making ore much less desirable than metal that has already been
refined.

Magic and alchemy is heavily employed to smelt, refine, harden, anneal, and
otherwise treat metals. Magic is also used to transmute metals and minerals,
although this is expensive.


==== Stone

As with metal, stone can be mined from certain areas of the Dungeon. Some
monsters also carry stone. Certain monster parts can be transmuted into stone
by magic.


==== Wood

As with metal, the Dungeon is the only real source of wood for tools and fuel.
Some monsters have wooden tools and weapons from which the woods can be
salvaged. On rare occasions "wooden" monsters such as treants can be
encountered. Such monsters are highly valuable.

Magic is heavily used to create wood from bone or similar materials.

Enterprising adventurers have tried going out into the Forest, but these never
come back if traveling out of sight of the City.


==== Fuel

Most wood found in the Dungeon is used to craft items, furniture, etc. Certain
inedible monster parts are sometimes dried out and turned into "charcoal" to be
used as fuel. Moreover, a number of monsters have fat, blubber, and oil
deposits that can be used as fuel.

Some other-worldly monsters such as fire elementals and salamanders can be
harnessed as sources of heat.

As with wood and metal, some intelligent monsters carry fuel sources such as
oil, coal and charcoal. Where they these fuel sources is a mystery.

Fires are always utilized as much as possible; Whenever a fire is lit, one
would smoke meats in the chimney, cook something and/or heat stones to
preserve the heat for later use. Many people also create their own charcoal
whenever they light fires.
